const actions = {
  GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_ERROR: "GET_POSTS_ERROR",
  GET_POST_REQUEST: "GET_POST_REQUEST",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_ERROR: "GET_POST_ERROR",
}

export default actions
