const actions = {
  GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_ERROR: "GET_POSTS_ERROR",
  GET_POST_REQUEST: "GET_POST_REQUEST",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_ERROR: "GET_POST_ERROR",
  PAGE_REQUEST: "GET_PAGE_REQUEST",
  PAGE_SUCCESS: "GET_PAGE_SUCCESS",
  PAGE_ERROR: "GET_PAGE_ERROR",
}

export default actions
